export const STAGE = process.env.STAGE;
const {
  JWT_SECRET,
  PBKDF2_SALT,
  DATABASE_ENCRYPT_KEY,
  KAKAO_REST_API_KEY,
  KAKAO_CLIENT_SECRET,
  COINMARKET_CAP_KEY,
  ARBITRUM_PRIVATE_KEY,
  N3_PRIVATE_KEY,
  ALIGO_API_KEY,
  ALIGO_SENDER_KEY,
  GIFTISHOW_CERT_KEY,
  GIFTISHOW_TOKEN_KEY,
  DOLLAR_BOX_PROCESS_KEY,
  TNK_POINT_KEY,
  ADPOPCORN_POINT_KEY,
  PINCRUX_POINT_KEY,
  TWITTER_SECRET_KEY,
  TWITTER_CLIENT_ID,
  TWEETSCOUT_API_KEY,
  REDIS_HOST,
  REDIS_PASSWORD,
  KEEP_IT_DATABASE_HOST,
  KEEP_IT_DATABASE_NAME,
  KEEP_IT_DATABASE_USER,
  KEEP_IT_DATABASE_PASSWORD,
  KEEP_IT_DATABASE_ENCRYPT_KEY,
  KEEP_IT_DATABASE_PORT,
  TOON_DIARY_DATABASE_HOST,
  TOON_DIARY_DATABASE_NAME,
  TOON_DIARY_DATABASE_USER,
  TOON_DIARY_DATABASE_PASSWORD,
  TOON_DIARY_DATABASE_ENCRYPT_KEY,
  TOON_DIARY_DATABASE_PORT,
  TOON_DIARY_OPENAI_API_KEY,
  HERMES_API_KEY,
  SERPAPI_API_KEY,
  NOTION_API_KEY,
  NOTION_DATABASE_ID,
  BAKE_BACKEND_URL,
  DAILY_BRIEFING_API_KEY,
} = process.env;

export {
  JWT_SECRET,
  PBKDF2_SALT,
  DATABASE_ENCRYPT_KEY,
  KAKAO_REST_API_KEY,
  KAKAO_CLIENT_SECRET,
  COINMARKET_CAP_KEY,
  ARBITRUM_PRIVATE_KEY,
  N3_PRIVATE_KEY,
  ALIGO_API_KEY,
  ALIGO_SENDER_KEY,
  GIFTISHOW_CERT_KEY,
  GIFTISHOW_TOKEN_KEY,
  DOLLAR_BOX_PROCESS_KEY,
  TNK_POINT_KEY,
  ADPOPCORN_POINT_KEY,
  PINCRUX_POINT_KEY,
  TWITTER_SECRET_KEY,
  TWITTER_CLIENT_ID,
  TWEETSCOUT_API_KEY,
  REDIS_HOST,
  REDIS_PASSWORD,
  KEEP_IT_DATABASE_HOST,
  KEEP_IT_DATABASE_NAME,
  KEEP_IT_DATABASE_USER,
  KEEP_IT_DATABASE_PASSWORD,
  KEEP_IT_DATABASE_ENCRYPT_KEY,
  KEEP_IT_DATABASE_PORT,
  TOON_DIARY_DATABASE_HOST,
  TOON_DIARY_DATABASE_NAME,
  TOON_DIARY_DATABASE_USER,
  TOON_DIARY_DATABASE_PASSWORD,
  TOON_DIARY_DATABASE_ENCRYPT_KEY,
  TOON_DIARY_DATABASE_PORT,
  TOON_DIARY_OPENAI_API_KEY,
  HERMES_API_KEY,
  SERPAPI_API_KEY,
  NOTION_API_KEY,
  NOTION_DATABASE_ID,
  BAKE_BACKEND_URL,
  DAILY_BRIEFING_API_KEY,
};

export function isLive() {
  return STAGE === 'live';
}

export function isAlpha() {
  return STAGE === 'alpha';
}

export const DATABASE_CONFIG = () =>
  ({
    host: process.env.DATABASE_HOST,
    port: Number(process.env.DATABASE_PORT) || 5432,
    username: process.env.DATABASE_USER,
    password: process.env.DATABASE_PASSWORD,
    database: process.env.DATABASE_NAME,
  } as const);

export const KEEP_IT_DATABASE_CONFIG = () =>
  ({
    host: process.env.KEEP_IT_DATABASE_HOST,
    port: Number(process.env.KEEP_IT_DATABASE_PORT) || 5432,
    username: process.env.KEEP_IT_DATABASE_USER,
    password: process.env.KEEP_IT_DATABASE_PASSWORD,
    database: process.env.KEEP_IT_DATABASE_NAME,
  } as const);
